import React from "react";
import {cookies} from "next/headers";
import type {Metadata} from "next";

import {SidebarProvider} from "@/components/ui/sidebar";
import {ThemeProvider} from "@/components/providers/theme-providers";
import {AppSideBar} from "@/features/dashboard/components/app-side-bar";
import {NavBar} from "@/features/dashboard/components/nav-bar";
import {UserProvider} from "@/components/user-context";


export const metadata: Metadata = {
    title: "Al-Hillan Academy Admin Dashboard",
    // description: "Generated by create next app",
};

const DashboardLayout = async ({
                                   children,
                               }: Readonly<{
    children: React.ReactNode;
}>) => {

    const cookieStore = await cookies()
    const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"

    return (
        <UserProvider>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <SidebarProvider defaultOpen={defaultOpen}>
                    <AppSideBar/>
                    <main className="w-full">
                        <NavBar/>
                        <div className="px-4">{children}</div>
                    </main>
                </SidebarProvider>
            </ThemeProvider>
        </UserProvider>

    );
}
export default DashboardLayout;