"""test

Revision ID: d45cbf355ca3
Revises: 
Create Date: 2025-05-07 15:35:25.537396

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'd45cbf355ca3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
